### ISSUE TITLE
[Feature Request] Support for 'LaTeX' based text formatting

### ISSUE THREAD

**Issue by adityausathe** [jgraph/draw.io#121]
Currently, draw.io provides basic text formatting options. It would be great if we get support for LaTeX text formatting. It will become convenient to write mathematical labels.

**Comment by alderg** [comment]
Extras, Mathematical Typesetting.

**Comment by RoyiAvital** [comment]
Any chance having this feature?

**Comment by RoyiAvital** [comment]
@davidjgraph , Is there a reason why you always delete my posts?
I couldn't locate any email of yours, so I use GitHub.

Thank You.

**Comment by davidjgraph** [comment]
Don't worry, I delete everyone's posts, not just yours 8-)

So, in this case you posted "Any chance having this feature?". This issue is closed with a pointer to where the feature is found. Why are you asking for a feature that exists? If you don't feel the feature is implemented the comment needs to explain why, or a new issue by opened explaining what feature is requested and detail how it differs.

**Comment by RoyiAvital** [comment]
It is indeed my bad, I overlooked this feature.
Amazing project!

Thank You.
