### ISSUE TITLE
Can't load diagram - loops requesting googleapis with 403 response

### ISSUE THREAD

**Issue by chatch** [jgraph/draw.io#24]
Loading a diagram on draw.io results in the attached errors. Last week this was working fine but in the last few days this failure has started. The same error occurs navigating from google docs or going directly to draw.io and creating a new diagram.

![draw io errors](https://cloud.githubusercontent.com/assets/1477978/19916069/565dd716-a0e9-11e6-811d-6bf1f299cda1.png)

**Comment by chatch** [comment]
Ah ok maybe this is CORS domain policy on google drive. See the response JSON here:

{error: {errors: [{domain: "global", reason: "domainPolicy",…}], code: 403,…}}
error
:
{errors: [{domain: "global", reason: "domainPolicy",…}], code: 403,…}
code
:
403
errors
:
[{domain: "global", reason: "domainPolicy",…}]
0
:
{domain: "global", reason: "domainPolicy",…}
message
:
"The domain policy has disabled third-party Drive apps"

**Comment by chatch** [comment]
Raised with google via feedback too.

**Comment by davidjgraph** [comment]
Your administrator has disabled third-party app on your GSuite domain. See https://support.google.com/a/answer/6089179?hl=en and https://support.google.com/a/answer/6105699?hl=en. Your admin can whitelist just draw.io to get it working again. If they need to have a conversion with us about app security get them to email us on support@draw.io.

I'll close this issue since Github issues is more for development issues.

**Comment by chatch** [comment]
great stuff, thank you for that.

**Comment by davidjgraph** [comment]
https://drawio.atlassian.net/browse/DP-5

**Comment by davidjgraph** [comment]
In the admin.google.com panel the setting is under Apps->GSuite->Drive and Docs->Data Access->"Allow users to access Google Drive with the Drive SDK API"
