### ISSUE TITLE
Client side printing missmatch preview and printout (A4 landscape)

### ISSUE THREAD

**Issue by poVoq** [jgraph/draw.io#28]
Client side printing is behaving strangely when I want to print a landscape A4 diagram.

I tried it both with Firefox and Chrome and different printers (pdf and actual) and all give the same result, the draw.io build in preview shows the correct size of the drawing, but the printouts (and the Chrome print preview) shows it reduced in size to about 80% or so. I tried playing around with various paper and scaling settings, but it it not possible to fix it it seems.

This is on Windows 8.1 by the way, running Draw.io 6.0.1.2 on an Ubuntu 16.04 server.

**Comment by sthag** [comment]
I' also struggling with this behavior.
I'm on Windows 10 using Chrome 59 or Firefox 54 (64bit).

I made some screenshots because they really speak for them self. The print dialogue does not have the correct size set up in the document.
As @poVoq mentioned the preview displays correctly but the result is scaled down.
It is not only happening to landscape documents, but also portrait shows the same behavior.

![](https://zauberkiste.interaktionsweise.de/index.php/s/gOCvWDwl2QrqJzp/download)
![](https://zauberkiste.interaktionsweise.de/index.php/s/SpNIwzwShJGg2bQ/download)
![](https://zauberkiste.interaktionsweise.de/index.php/s/pa8E9JgtPmnIlhs/download)
![](https://zauberkiste.interaktionsweise.de/index.php/s/6bd3Htpn1gLpSrP/download)
![](https://zauberkiste.interaktionsweise.de/index.php/s/YovWgGAN2SmZ5kR/download)
![](https://zauberkiste.interaktionsweise.de/index.php/s/PzMtNTkv8UOo8NS/download)

It is quite annoying because it is not possible to maximize a document on the page size. The dynamic expansion of the page during editing is great but the borders/size does not resemble the actual page size for printing out the document.

**Comment by alderg** [comment]
This is a known issue. Try tuning the page scale value in the print dialog to improve the results.
