### ISSUE TITLE
sandstorm version update

### ISSUE THREAD

**Issue by ertanalytics** [jgraph/draw.io#43]
Looks like sandstorm app market pull is still on 5.6.0.3.  I see the version you have 6.0.2.5 release for sandstorm in the  /etc/ folder and was hoping to use this great software on my personal cloud for many projects.  Hope to see it get pulled or pushed or anything I can do to help, please let me know.

**Comment by davidjgraph** [comment]
We're looking for someone to take over releasing the sandstorm version. It's mostly just a case of building the draw.io latest and submitting it, but we always run into Sandstorm build issues because we're not familiar with the platform and it just sucks hours of time we don't have up.

**Comment by ertanalytics** [comment]
I am happy to do it.  I plan on using it a lot and could really use the tool.  I have coding experience in several languages and believe I could figure it out.  I also know the sandstorm team is very responsive for their other tools and interested in having this tool available, so I should be able to get some help from them figuring out issues.  Please let me know what information you might need from me if you decide to proceed.

**Comment by ocdtrekkie** [comment]
The last commit to fix draw.io's Sandstorm implementation is here: https://github.com/jgraph/draw.io/commit/47e26e5d94514e3bf1a1be9395d809615b1146f1

It should point you in the direction of where the Sandstorm-specific files in the repo are, and what sort of change had to be made for the last release, which I believe also included a rotation of draw.io's signing key.

While I suppose it's up to @davidjgraph, my hope is that he's still going to sign the package, but that perhaps if you set up a build environment, and update the Sandstorm-specific code to the latest version, test everything new out in Sandstorm, so all he has to do is run the "spk pack" command, that it'd be burden-free enough.

As a note, I'm willing to help myself as well, but I've never been able to set up a Sandstorm build environment that can handle raw API apps like draw.io, so I have a feeling I wouldn't be the best person to do this directly.

**Comment by davidjgraph** [comment]
@ertanalytics The build should currently be stable. Kenton added a change to compress served resources, that isn't public yet. The main problem is getting the right capnp and sandstorm versions to get the thing building. There are instructions are https://github.com/jgraph/draw.io/tree/master/etc/sandstorm, but last time I tried them I got an stack trace when creating a new draw.io grain instead of the editor.

You shouldn't need to make any coding changes, it's just a case of building the latest from github to update the Sandstorm version with new features.

Getting the thing to build can be a big time sink unless you're familiar with the ins and outs of sandstorm. In retrospect I think it was the wrong decision to work directly against the raw API. Given nobody else is doing this there's nobody to hit issues before we do and every attempt to do a "quick update" goes wrong.

Adding a Node server might well be the best long term solution, since that also gives us real-time collaboration (assuming the server can be left running).

@ocdtrekkie the build environment is a problem for us as well, we haven't been able to get it working reliably. The draw.io integration is easy for us, it's the environment and test/releasing we struggle to find the time for.

**Comment by ocdtrekkie** [comment]
@davidjgraph That sounds like fundamentally something @paulproteus should be addressing. Not just for you, but for Sandstorm in general. The raw API _is_ the "best" way to plug into Sandstorm, and so really it _should_ be better supported. I'd be a little sad to see a working raw API app move to Node and the HTTP-Bridge.

**Comment by davidjgraph** [comment]
I don't think it can be addressed without a number of third-party integrations using it in production and hitting the real pain points, it's just we don't really want to suffer much of that. Also, in fairness, the whole thing is beta and prone to moving around as such.
